#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HandDrawTest.Resource", IsApplication=true)]

namespace HandDrawTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int blue = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int blur = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int emboss = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int green = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int hand_draw_view = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int red = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int width_1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int width_3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int width_5 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int my_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int blur = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int color = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int color_blue = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int color_green = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int color_red = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int emboss = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int width = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int width_1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int width_3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int width_5 = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
